# MySQL Configuration

host: localhost
port: 3306
user: root
password: mysql
database: myapp_mysql
sslmode: disable

cloudsql:
  enabled: false
  project: your-gcp-project
  region: asia-northeast1
  instance: mysql-instance
  private_ip: false
